### ISSUE TITLE
Adicionar novo parâmetro no cURL

### ISSUE THREAD

**Issue by everaldoscabral** [alexandremjcastro/Zabbix#1]
Agora é preciso enviar cookies para realizar o download das informações, para solucionar basta adicionar o seguinte comando no início do comando cURL:

-b 'session='

![image](https://user-images.githubusercontent.com/53796085/153326473-f9c31df7-a083-42c4-bc76-40910285a4f8.png)

**Comment by xandtux** [comment]
Corrigido. Muito obrigado pela contribuição.
